### PR TITLE
Better onboarding experience in `url/getting-started`

### PR DESCRIPTION
**Pull request by calejvaldez**
# Why a rewrite?

The on-boarding experience in `url/getting-started` is less of onboard instructions and more of just a setup without proving any background to the project. This rewrite will improve on-boarding for future members.

Early thanks to @AyushJain2021 for bringing this up.

## Needed changes

- [ ] Introduce the actual project
  - [ ] Give background of the advisor, team leads, etc.
  - [x] Explain what hospice care is
  - [x] Explain the problems we identified in hospice
  - [x] Introduce the solutions we're trying to develop
- [x] Continue with the actual setup
  - [x] Technical stuff (calendar, emails, etc.)
  - [x] Bash/Debian/etc. setups
- [x] Provide supplemental material
  - [x] Interview notes
  - [x] Requirements
  - [x] Other stuff we might want to introduce them to

❓ See anything we're missing? Please add a comment below!

## Instructions for the Developers team

If you want to work on this, please run the following commands:

```shell
# If you haven't already, clone the repo
git clone git@github.com:ojosproject/docs.git

# Switch to this branch
git switch url/getting-started-rewrite
```

**All** commits must be done on the `url/getting-started-rewrite` branch in order to appear in this pull request.

If you have any questions, please comment below. Thanks!

### CODE REVIEW

**Comment by calejvaldez** [comment]
"Background" part of this almost done, though I want to get @Electric108's background in this too since he's the Engineering lead.

**Comment by AyushBot412** [comment]
As of right now, it looks good, I think with @Electric108's additions and background, along with a complete technical set up, it should be fine and dandy.

**Comment by calejvaldez** [comment]
I think for the other super technical stuff like Debian and SSH keys shouldn't be added to the main document. I feel like it's better to just have that setup as a team thing since Engineering doesn't need Debian or SSH keys.

I also think the current docs for the Developers' setup document is fine. It links to other documents to make sure separate documents stay separate.

**Comment by calejvaldez** [comment]
In 99fc17956be1515af397f212bc76653e9b1b91c9, we merged this website to our main website, giving us only one Docusaurus instance to maintain. This PR is now being tracked here: https://github.com/ojosproject/website/pull/21

**Pull request closed without merging**
